apiVersion: apps/v1
kind: Deployment
metadata:
  name: teafiles-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: teafiles-service
  template:
    metadata:
      labels:
        app: teafiles-service
    spec:
      containers:
        - name: teafiles-service
          image: nami/teafiles-service
          imagePullPolicy: Never
          ports:
            - containerPort: 3005  # Thay $PORT bằng giá trị thích hợp
          envFrom:
            - configMapRef:
                name: teafiles-service-configmap
          # volumeMounts:
            # - name: app-volume
              # mountPath: /app
      volumes:
        - name: app-volume
          persistentVolumeClaim:
            claimName: teafiles-service-pvc
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: teafiles-service-configmap
data:
  # Đặt các biến môi trường từ file .env vào đây
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teafiles-service-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi  # Thay giá trị lưu trữ mong muốn
---
apiVersion: v1
kind: Service
metadata:
  name: teafiles-service-entrypoint
spec:
  type: NodePort
  selector:
    app: teafiles-service
  ports:
  - port: 3005
    targetPort: 3005
    nodePort: 30005