apiVersion: apps/v1
kind: Deployment
metadata:
  name: teafiles-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teafiles-service
  template:
    metadata:
      labels:
        app: teafiles-service
    spec:
      # initContainers:
      #   - name: init-rsync
      #     image: alpine:latest
      #     command: ["sh", "-c"]
      #     args:
      #       - apk update && apk add rsync && rsync -avz -e "ssh -i /etc/ssh/rsync-key" root@127.0.0.1:/mnt/volume_sgp1_04/teafiles_bak /app-volume
      #     volumeMounts:
      #       - name: app-volume
      #         mountPath: /app-volume
      #       - name: ssh-key
      #         mountPath: /etc/ssh/rsync-key
      #         subPath: rsync-key
      #     envFrom:
      #       - secretRef:
      #           name: rsync-private-key
      containers:
        - name: teafiles-service
          image: nami/teafiles-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3005
          envFrom:
            - configMapRef:
                name: teafiles-service-config
          volumeMounts:
            - name: app-volume
              mountPath: /app-volume
      volumes:
        - name: app-volume
          persistentVolumeClaim:
            claimName: teafiles-service-pvc
      # - name: ssh-key
      #   secret:
      #     secretName: rsync-private-key  # Tên của Secret chứa SSH key
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: teafiles-service-config
data:
  PORT: "3005"  # Thay đổi cổng nếu cần
  ROOT_PATH_TEA: "/app"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teafiles-service-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi  # Thay giá trị lưu trữ mong muốn
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: rsync-backup
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: rsync-container
              image: alpine:latest  # Hoặc hình ảnh chứa rsync
              command: ["sh", "-c"]
              args:
                - apk update && apk add rsync && rsync -avz -e "ssh -i /etc/ssh/rsync-key" root@127.0.0.1:/mnt/volume_sgp1_04/teafiles_bak /app-volume
              volumeMounts:
                - name: app-volume
                  mountPath: /app-volume
                - name: ssh-key
                  mountPath: /etc/ssh/rsync-key
                  subPath: rsync-key
              envFrom:
                - secretRef:
                    name: rsync-private-key
          volumes:
          - name: ssh-key
            secret:
              secretName: rsync-private-key  # Tên của Secret chứa SSH key
          - name: app-volume
            persistentVolumeClaim:
              claimName: teafiles-service-pvc
          restartPolicy: OnFailure
---
apiVersion: v1
kind: Service
metadata:
  name: teafiles-service
spec:
  type: LoadBalancer
  selector:
    app: teafiles-service
  ports:
    - name: http
      protocol: TCP
      port: 3005
      targetPort: 3005  # Thay đổi nếu cổng khác
---
# Nếu bạn muốn sử dụng Ingress để truy cập từ bên ngoài cluster
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: teafiles-service-ingress
spec:
  rules:
    - host: localhost  # Thay đổi tên miền
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: teafiles-service
                port:
                  number: 3005
