apiVersion: apps/v1
kind: Deployment
metadata:
  name: teafiles-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teafiles-service
  template:
    metadata:
      labels:
        app: teafiles-service
    spec:
      initContainers:
        - name: init-rsync
          image: alpine:latest # Hoặc hình ảnh chứa rsync
          command: ["sh", "-c"]
          args:
            - cp /etc/rsync-config/rsync-key /etc/rsync-key && chmod 600 /etc/rsync-key && apk update && apk add rsync openssh-client openssh && rsync -avzr -e "ssh -i /etc/rsync-key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" $(cat /etc/rsync-config/remote-server):/tmp/teafiles_bak /app-volume
          volumeMounts:
            - name: app-volume
              mountPath: /app-volume
            - name: rsync-config-volume
              mountPath: /etc/rsync-config
      containers:
        - name: teafiles-service
          image: nami/teafiles-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3005
          envFrom:
            - configMapRef:
                name: teafiles-service-config
          volumeMounts:
            - name: app-volume
              mountPath: /app-volume
      volumes:
        - name: app-volume
          persistentVolumeClaim:
            claimName: teafiles-service-pvc
        - name: rsync-config-volume
          secret:
            secretName: rsync-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: teafiles-service-config
data:
  PORT: "3005" # Thay đổi cổng nếu cần
  ROOT_PATH_TEA: "/app-volume"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teafiles-service-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi # Thay giá trị lưu trữ mong muốn
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: rsync-backup
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: rsync-container
              image: alpine:latest # Hoặc hình ảnh chứa rsync
              command: ["sh", "-c"]
              args:
                - cp /etc/rsync-config/rsync-key /etc/rsync-key && chmod 600 /etc/rsync-key && apk update && apk add rsync openssh-client openssh && rsync -avzr -e "ssh -i /etc/rsync-key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" $(cat /etc/rsync-config/remote-server):/tmp/teafiles_bak /app-volume
              volumeMounts:
                - name: app-volume
                  mountPath: /app-volume
                - name: rsync-config-volume
                  mountPath: /etc/rsync-config
          volumes:
            - name: app-volume
              persistentVolumeClaim:
                claimName: teafiles-service-pvc
            - name: rsync-config-volume
              secret:
                secretName: rsync-config
          restartPolicy: OnFailure
---
apiVersion: v1
kind: Service
metadata:
  name: teafiles-service
spec:
  type: LoadBalancer
  selector:
    app: teafiles-service
  ports:
    - name: http
      protocol: TCP
      port: 3005
      targetPort: 3005 # Thay đổi nếu cổng khác
---
# Nếu bạn muốn sử dụng Ingress để truy cập từ bên ngoài cluster
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: teafiles-service-ingress
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: teafiles-service
                port:
                  number: 3005
